system("R CMD SHLIB *.c -lgeos_c")
system("R CMD SHLIB *.c -lgeos_c")
dyn.load("rgeos.so")
.Call("rgeos_Init")
library(sp)
data(meuse)
coordinates(meuse) <- c("x", "y")
zz <- .Call("rgeos_inout", meuse)
.Call("rgeos_finish")
dyn.unload("rgeos.so")
system("R CMD SHLIB *.c -lgeos_c")
dyn.load("rgeos.so")
.Call("rgeos_Init")
zz <- .Call("rgeos_inout", meuse)
str(zz)
c(bbox(meuse))
all.equal(as(meuse, "SpatialPoints"), zz)
savehistory("tues091110.Rhistory")

library(sp)
p1 <- cbind(x=c(0, 0, 10, 10, 0), y=c(0, 10, 10, 0, 0))
p2 <- cbind(x=c(3, 3, 7, 7, 3), y=c(3, 7, 7, 3, 3))
p3 <- cbind(x=c(20, 20, 30, 30, 20), y=c(20, 30, 30, 20, 20))
Pls <- Polygons(list(Polygon(p1), Polygon(p2), Polygon(p3)), ID="1")

.Call("rgeos_what", Pls)

library(maptools)
Pls1 <- checkPolygonsHoles(Pls)

